<?php

use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Вставляем данные в таблицу.
        DB::table('transactions')->insert($this->getData());
    }

    /**
     * Возвращаем массив с данными для заполнения.
     * @return string[][]
     */
    private function getData()
    {
        return [
            [
                'user_id' => 1,
                'type' => User::TYPE_INCOME,
                'amount' => 12560.20,
                'date' => '2020-07-01 10:56:27',
                'comment' => null,
                'wallet_id_from' => null,
                'wallet_id_to' => 2,
                'income_id' => 1,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 805.00,
                'date' => '2020-07-02 12:33:27',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 2,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_EXPENSE,
                'amount' => 55.60,
                'date' => '2020-07-03 08:06:02',
                'comment' => null,
                'wallet_id_from' => 4,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 5,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_EXPENSE,
                'amount' => 606.99,
                'date' => '2020-07-03 08:54:22',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 4,
                'tag_id' => 3,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_TRANSFER,
                'amount' => 1000.00,
                'date' => '2020-07-04 14:32:07',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => 4,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_TRANSFER,
                'amount' => 5000.00,
                'date' => '2020-07-05 14:42:17',
                'comment' => null,
                'wallet_id_from' => 2,
                'wallet_id_to' => 1,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 2000.00,
                'date' => '2020-07-06 20:34:22',
                'comment' => 'Положил деньги на телефон детям',
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 333.99,
                'date' => '2020-07-07 09:01:22',
                'comment' => null,
                'wallet_id_from' => 2,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 2,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_INCOME,
                'amount' => 7822.00,
                'date' => '2020-07-08 11:21:36',
                'comment' => 'За прошлый месяц',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 5,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-08 22:01:22',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 6,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_INCOME,
                'amount' => 12560.20,
                'date' => '2020-07-11 10:56:27',
                'comment' => null,
                'wallet_id_from' => null,
                'wallet_id_to' => 2,
                'income_id' => 2,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 500.00,
                'date' => '2020-07-12 12:01:22',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 217.00,
                'date' => '2020-07-12 12:05:02',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => null,
            ],
            [
                'user_id' => 1,
                'type' => User::TYPE_EXPENSE,
                'amount' => 903.54,
                'date' => '2020-07-12 12:05:02',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 1,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_INCOME,
                'amount' => 22000.00,
                'date' => '2020-07-19 11:20:36',
                'comment' => 'Первый транш',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 4,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_INCOME,
                'amount' => 24000.00,
                'date' => '2020-07-19 11:34:56',
                'comment' => 'Второй транш',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 4,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-19 12:08:22',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 4,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_TRANSFER,
                'amount' => 10000.00,
                'date' => '2020-07-19 14:32:07',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => 4,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
            ],
            [
                'user_id' => 2,
                'type' => User::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-19 15:20:01',
                'comment' => null,
                'wallet_id_from' => 4,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 5,
                'tag_id' => null,
            ],
        ];
    }
}
