<?php

use App\Models\Transaction;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Вставляем данные в таблицу.
        DB::table('transactions')->insert($this->getData());
    }

    /**
     * Возвращаем массив с данными для заполнения.
     * @return string[][]
     */
    private function getData()
    {
        return [
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_INCOME,
                'amount' => 12560.20,
                'date' => '2020-07-01',
                'comment' => null,
                'wallet_id_from' => null,
                'wallet_id_to' => 2,
                'income_id' => 1,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 805.00,
                'date' => '2020-07-02',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 2,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 55.60,
                'date' => '2020-07-03',
                'comment' => null,
                'wallet_id_from' => 4,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 5,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 606.99,
                'date' => '2020-07-03',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 4,
                'tag_id' => 3,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_TRANSFER,
                'amount' => 1000.00,
                'date' => '2020-07-04 ',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => 4,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_TRANSFER,
                'amount' => 5000.00,
                'date' => '2020-07-05',
                'comment' => null,
                'wallet_id_from' => 2,
                'wallet_id_to' => 1,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 2000.00,
                'date' => '2020-07-06',
                'comment' => 'Положил деньги на телефон детям',
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 333.99,
                'date' => '2020-07-07',
                'comment' => null,
                'wallet_id_from' => 2,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 2,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_INCOME,
                'amount' => 7822.00,
                'date' => '2020-07-08',
                'comment' => 'За прошлый месяц',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 5,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-08',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 6,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_INCOME,
                'amount' => 12560.20,
                'date' => '2020-07-11',
                'comment' => null,
                'wallet_id_from' => null,
                'wallet_id_to' => 2,
                'income_id' => 2,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 500.00,
                'date' => '2020-07-12',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 217.00,
                'date' => '2020-07-12',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 903.54,
                'date' => '2020-07-12',
                'comment' => null,
                'wallet_id_from' => 3,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 1,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_INCOME,
                'amount' => 22000.00,
                'date' => '2020-07-19',
                'comment' => 'Первый транш',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 4,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_INCOME,
                'amount' => 24000.00,
                'date' => '2020-07-19',
                'comment' => 'Второй транш',
                'wallet_id_from' => null,
                'wallet_id_to' => 6,
                'income_id' => 4,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-19',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 4,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_TRANSFER,
                'amount' => 10000.00,
                'date' => '2020-07-19',
                'comment' => null,
                'wallet_id_from' => 6,
                'wallet_id_to' => 4,
                'income_id' => null,
                'expense_id' => null,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 2,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 1705.21,
                'date' => '2020-07-19',
                'comment' => null,
                'wallet_id_from' => 4,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 5,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 1200.05,
                'date' => '2020-06-19',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 1,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 3705.21,
                'date' => '2020-06-06',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 1,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 602.17,
                'date' => '2020-06-12',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 2,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 999.99,
                'date' => '2020-06-17',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => 1,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 60.00,
                'date' => '2020-06-19',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 2,
                'tag_id' => null,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 400.00,
                'date' => '2020-06-27',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
                "updated_at" => "2020-06-24 10:14:48",
                "created_at" => "2020-06-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 400.00,
                'date' => '2020-07-21',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 3,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
            [
                'user_id' => 1,
                'type' => Transaction::TYPE_EXPENSE,
                'amount' => 712.50,
                'date' => '2020-07-22',
                'comment' => null,
                'wallet_id_from' => 1,
                'wallet_id_to' => null,
                'income_id' => null,
                'expense_id' => 1,
                'tag_id' => null,
                "updated_at" => "2020-07-24 10:14:48",
                "created_at" => "2020-07-24 10:14:48",
            ],
        ];
    }
}
